### PR TITLE
Update list of supported languages.

### PR DESCRIPTION
**Pull request by josteink**
Updated according to recognized extensions in the actual pre-commit file.

### CODE REVIEW

**Review by kvz — APPROVED** [review]

**Comment by kvz** [comment]
Thanks! Wanted to merge but can’t via mobile cause there is a CI fail, will check it later behind the big screen!

**Comment by josteink** [comment]
> Should have been able to commit a .es6 without syntax errors
928make: *** [test] Error 1
929The command "make test" exited with 2.

Seems like the linter-tests for es6 needs updating. They no longer pass with latest version of the linter.

**Comment by josteink** [comment]
With that I mean trying to retrigger a CI build for current master will probably fail too.

I see @abtris added the ES6 support in https://github.com/kvz/ochtra/commit/6e585a320ea3c29b62f1862d1d202b0aec3a31cb.

Should he fix this, or do you plan to do that?

**Comment by abtris** [comment]
I will check where is problem.

**Comment by abtris** [comment]
I think we need make a few changes. For example node6 is not supported anymore. Node 10 is now stable. 
I'm thinking if we remove jshint and stay only on eslint for javascript.

**Comment by kvz** [comment]
+💯

**Comment by abtris** [comment]
#23 will fix issue, was change in ubuntu that remove xmllint tool from basic toolchain.

**Comment by kvz** [comment]
Merged! 🙏

**Comment by josteink** [comment]
Awesome. Thanks.

**Comment by josteink** [comment]
Awesome. Thanks.

I'll rebase my fix on that branch, and then the CI for this build should be green too :)

**Comment by kvz** [comment]
👍💥

**Comment by josteink** [comment]
And green.

**Comment by kvz** [comment]
Appreciated!!

**Pull request merged**
